version: "3.6"
services:
  postgres-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    expose:
      - "5432"
  pgadmin-compose:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - "postgres-db"
  graphql-engine:
    image: hasura/graphql-engine:v2.2.1
    ports:
      - "8080:8080"
    depends_on:
      - "postgres-db"
    restart: always
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET
      - HASURA_GRAPHQL_DATABASE_URL
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES
      - HASURA_GRAPHQL_JWT_SECRET
  petapp-backend:
    image: binhtt13122000/petcare-be:latest
    restart: always
    container_name: petcare-be
    depends_on:
      - "postgres-db"
    ports:
      - "4000:4000"
    expose:
      - "4000"
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - API_PORT
      - API_ROOT_URL
      - WEB_ADMIN_ROOT_URL
      - HASURA_ROOT_URL
      - BUCKET
      - REDIS_SERVER
      - BCRYPT_SALT
      - API_PREFIX
      - JWT_SECRET_KEY
      - JWT_EXPIRES_IN
      - ACCESS_TOKEN_SECRET
      - ACCESS_TOKEN_EXPIRATION
      - REFRESH_TOKEN_SECRET
      - REFRESH_TOKEN_EXPIRATION
      - VNPAY_TMN_CODE
      - VNPAY_HASH_SECRET
      - VNPAY_URL
      - VNPAY_VERSION
      - MONGO_CONNECTION_STRING
  redis-server:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  db_data:
  redis-data: