version: "3.6"
services:
    postgres:
        image: postgres:13
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
        ports:
            - "5432:5432"
        expose:
            - "5432"
    pgadmin-compose:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "16543:80"
        depends_on:
            - "postgres"
    graphql-engine:
        image: hasura/graphql-engine:v2.2.1
        ports:
            - "8080:8080"
        depends_on:
            - "postgres"
        restart: always
        environment:
            - HASURA_GRAPHQL_ADMIN_SECRET
            - HASURA_GRAPHQL_DATABASE_URL
            - HASURA_GRAPHQL_ENABLE_CONSOLE
            - HASURA_GRAPHQL_DEV_MODE
            - HASURA_GRAPHQL_ENABLED_LOG_TYPES
            - HASURA_GRAPHQL_JWT_SECRET
    petapp-backend:
        image: binhtt13122000/petcare-be:latest
        restart: always
        depends_on:
            - "postgres"
        ports:
            - "4000:4000"
        expose:
            - "4000"
        environment:
            - POSTGRES_HOST
            - POSTGRES_PORT
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
            - API_PORT
            - API_ROOT_URL
            - WEB_ADMIN_ROOT_URL
            - HASURA_ROOT_URL
            - BUCKET
            - REDIS_SERVER
            - BCRYPT_SALT
            - API_PREFIX
            - JWT_SECRET_KEY
            - JWT_EXPIRES_IN
            - ACCESS_TOKEN_SECRET
            - ACCESS_TOKEN_EXPIRATION
    redis-server:
        image: redis
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        restart: always
    # admin_web:
    #     image: binhtt13122000/admin_pet_app:latest
    #     ports:
    #         - "3000:3000"
    #     expose:
    #         - "3000"
    #     depends_on:
    #         - "petapp-backend"
    #     environment:
    #         - NEXT_PUBLISH_API_ROOT_URL
    #         - NEXT_PUBLIC_HASURA_ADMIN_SECRET
    #         - NEXT_PUBLIC_HASURA_END_POINT
    #         - API_ROOT_URL
    #         - HASURA_ADMIN_SECRET
    #         - HASURA_END_POINT
    #         - NEXT_PUBLIC_API_KEY
    #         - NEXT_PUBLIC_AUTH_DOMAIN
    #         - NEXT_PUBLIC_PROJECT_ID
    #         - NEXT_PUBLIC_STORAGE_BUCKET
    #         - NEXT_PUBLIC_MESSAGING_SENDER_ID
    #         - NEXT_PUBLIC_APP_ID
    #         - NEXT_PUBLIC_MEASUREMENT_ID
    #         - NEXT_PUBLISH_CLOUD_MESSAGING_TOKEN
    #     restart: always
volumes:
    db_data:
    redis-data: